server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

spring:
  application:
    name: spring cloud gateway
  cloud:
   gateway:
#      global-cors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: http://localhost:4200/
#            allowedMethods:
#              - GET
#              - POST
#              - PATCH
#              - DELETE
#            allowed-headers:
#              - Content-Type
      routes:
        - id: weather-service
          uri: lb://weather-service
          predicates:
            - Path=/weather/**
