server:
  port: 8080

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true


zuul:
  routes:
    weather-service:
      serviceId: weather-service
      path: /weather/**

  host:
    socket-timeout-millis: 30000

management:
  endpoints:
    web:
      exposure:
        include: '*'